'use client';
import { useEffect, useState } from 'react';
import { Shell } from '@/components/shell';
import { getSupabaseBrowserClient } from '@/lib/supabase';

type Assignment={id:string;class_id:string|null;title:string;description:string|null;deadline:string|null;classes?:{name:string}[]|null};
type Submission={id:string;assignment_id:string;drive_file_id:string|null;submitted_at:string;grade:number|null;feedback:string|null;status:string|null};
export default function TugasPage(){
 const [assignments,setAssignments]=useState<Assignment[]>([]),[submissions,setSubmissions]=useState<Submission[]>([]),[role,setRole]=useState(''),[userId,setUserId]=useState(''),[query,setQuery]=useState(''),[open,setOpen]=useState<string|null>(null),[loading,setLoading]=useState(true),[uploading,setUploading]=useState<string|null>(null),[message,setMessage]=useState('');
 useEffect(()=>{(async()=>{const sb=getSupabaseBrowserClient();if(!sb)return;const {data:{user}}=await sb.auth.getUser();if(!user)return;setUserId(user.id);const {data:p}=await sb.from('profiles').select('role,class_id').eq('id',user.id).maybeSingle();if(!p)return;setRole(p.role||'');const q=p.role==='siswa'&&p.class_id?sb.from('assignments').select('id,class_id,title,description,deadline,classes(name)').eq('class_id',p.class_id).order('deadline',{ascending:true}):sb.from('assignments').select('id,class_id,title,description,deadline,classes(name)').order('deadline',{ascending:true});const {data:a}=await q;const {data:s}=p.role==='siswa'?await sb.from('submissions').select('id,assignment_id,drive_file_id,submitted_at,grade,feedback,status').eq('student_id',user.id):{data:[] as Submission[]};setAssignments((a||[]) as Assignment[]);setSubmissions((s||[]) as Submission[]);setLoading(false)})()},[]);
 const submit=async(id:string,file:File)=>{const sb=getSupabaseBrowserClient();if(!sb||!userId)return;setUploading(id);setMessage('');const path=`${userId}/${id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error:u}=await sb.storage.from('task-submissions').upload(path,file,{upsert:true});if(u){setMessage(u.message);setUploading(null);return}const {data:old}=await sb.from('submissions').select('id').eq('assignment_id',id).eq('student_id',userId).maybeSingle();const payload={assignment_id:id,student_id:userId,drive_file_id:path,submitted_at:new Date().toISOString(),status:'submitted',updated_at:new Date().toISOString()};const {error:e}=old?await sb.from('submissions').update(payload).eq('id',old.id):await sb.from('submissions').insert(payload);if(e)setMessage(e.message);else{setMessage('Tugas berhasil dikumpulkan.');setOpen(null)}setUploading(null)};
 const filtered=assignments.filter(a=>(a.title+' '+(a.description||'')+' '+(a.classes?.[0]?.name||'')).toLowerCase().includes(query.toLowerCase()));
 return <Shell><div className="container"><section className="page-head"><div className="eyebrow">Assignments</div><h1>Tugas & Pengumpulan</h1><p>Data tugas dan submission berasal langsung dari Supabase.</p></section><section className="section"><div className="toolbar"><input className="input" placeholder="Cari tugas..." value={query} onChange={e=>setQuery(e.target.value)}/><span className="status">{loading?'Memuat...':`${filtered.length} tugas`}</span></div>{message&&<div className="status status-green" style={{marginBottom:14}}>{message}</div>}<div className="grid">{filtered.map(a=>{const s=submissions.find(x=>x.assignment_id===a.id);return <article className="card task" key={a.id}><div><span className="tag">{a.classes?.[0]?.name||'Kelas'}</span><h3>{a.title}</h3><p>{a.description||'Tidak ada deskripsi.'}</p><p><strong>Deadline:</strong> {a.deadline?new Date(a.deadline).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'}):'Tidak ditentukan'}</p>{role==='siswa'&&<><span className={`status ${s?'status-green':''}`}>{s?(s.grade!==null?`Nilai: ${s.grade}`:'Terkirim'):'Belum dikumpulkan'}</span>{s?.feedback&&<p className="muted">Feedback: {s.feedback}</p>}</>}</div>{role==='siswa'&&<div><button className="button button-dark" onClick={()=>setOpen(open===a.id?null:a.id)}>{open===a.id?'Tutup':s?'Ganti submission':'Kumpulkan'}</button></div>}{open===a.id&&<div style={{gridColumn:'1/-1',borderTop:'1px solid var(--line)',paddingTop:18}}><input type="file" className="input" onChange={e=>{const f=e.target.files?.[0];if(f)void submit(a.id,f)}} disabled={uploading===a.id}/>{uploading===a.id&&<p className="muted">Mengunggah...</p>}</div>}</article>})}</div>{!loading&&!filtered.length&&<div className="card">Belum ada tugas untuk data akun ini.</div>}</section></div></Shell>}
