'use client';
import { useEffect,useState } from 'react';
import { Shell } from '@/components/shell';
import { RoleGuard } from '@/components/role-guard';
import { getSupabaseBrowserClient } from '@/lib/supabase';
type UserRow={id:string;full_name:string|null;role:string;class_id:string|null;email?:string};type ClassRow={id:string;name:string};
export default function AdminUsers(){const [users,setUsers]=useState<UserRow[]>([]),[classes,setClasses]=useState<ClassRow[]>([]),[form,setForm]=useState({full_name:'',email:'',password:'',role:'student',class_id:''}),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const load=async()=>{const sb=getSupabaseBrowserClient();if(!sb)return;const [{data:u},{data:c}]=await Promise.all([sb.from('profiles').select('id,full_name,role,class_id').order('full_name'),sb.from('classes').select('id,name').order('name')]);setUsers((u||[]) as UserRow[]);setClasses((c||[]) as ClassRow[]);setLoading(false)};useEffect(()=>{void load()},[]);
 const create=async()=>{const sb=getSupabaseBrowserClient();if(!sb)return;setSaving(true);setError('');const {data,error:e}=await sb.functions.invoke('admin-create-user',{body:form});if(e||data?.error){setError(e?.message||data?.error||'Gagal membuat akun')}else{setForm({full_name:'',email:'',password:'',role:'student',class_id:''});setOpen(false);await load()}setSaving(false)};
 return <RoleGuard role="administrator"><Shell><div className="container"><section className="page-head"><div className="eyebrow">Administration</div><h1>Kelola pengguna.</h1><p>Buat akun siswa, guru, dan administrator melalui Supabase Auth + profiles.</p></section><section className="section"><div className="section-head"><div><div className="eyebrow">Users</div><h2 className="section-title">{users.length} pengguna</h2></div><button className="button button-dark" onClick={()=>setOpen(true)}>+ Pengguna baru</button></div>{error&&<div className="status status-red">{error}</div>}{open&&<div className="card" style={{marginBottom:18}}><div className="form"><label>Nama lengkap</label><input className="input" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><label>Email login</label><input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><label>Password awal</label><input className="input" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><div className="grid grid-2"><div><label>Role</label><select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="student">Siswa</option><option value="teacher">Guru</option><option value="administrator">Administrator</option></select></div><div><label>Kelas</label><select className="input" value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})}><option value="">Tidak ada</option>{classes.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div></div><button className="button button-yellow" disabled={saving||!form.full_name||!form.email||form.password.length<6} onClick={()=>void create()}>{saving?'Membuat...':'Buat akun'}</button> <button className="button" onClick={()=>setOpen(false)}>Batal</button></div></div>}<div className="card"><div className="table-like">{!loading&&users.map(u=><div className="row" key={u.id}><div><strong>{u.full_name||'Tanpa nama'}</strong><div className="muted">{u.id}</div></div><span className="tag">{u.role}</span><span>{classes.find(c=>c.id===u.class_id)?.name||'—'}</span></div>)}</div>{!loading&&!users.length&&<p className="muted">Belum ada pengguna.</p>}</div></section></div></Shell></RoleGuard>}
