'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { Shell } from '@/components/shell';
import { RoleGuard } from '@/components/role-guard';
import { getSupabaseBrowserClient } from '@/lib/supabase';

type Row={id:string;title:string;deadline:string|null;class_id:string|null;classes?:{name:string}[]|null};
type Submission={id:string;assignment_id:string;student_id:string;grade:number|null;feedback:string|null;submitted_at:string;drive_file_id:string|null;assignments?:{title:string}[]|null;profiles?:{full_name:string|null}[]|null};

export default function Guru(){
 const [tasks,setTasks]=useState<Row[]>([]),[subs,setSubs]=useState<Submission[]>([]),[materials,setMaterials]=useState(0),[loading,setLoading]=useState(true),[saving,setSaving]=useState<string|null>(null);
 useEffect(()=>{(async()=>{const sb=getSupabaseBrowserClient();if(!sb)return;const [{data:t},{data:s},{count:m}]=await Promise.all([sb.from('assignments').select('id,title,deadline,class_id,classes(name)').order('deadline',{ascending:true}),sb.from('submissions').select('id,assignment_id,student_id,grade,feedback,submitted_at,drive_file_id,assignments(title),profiles(full_name)').order('submitted_at',{ascending:false}),sb.from('materials').select('*',{count:'exact',head:true})]);setTasks((t||[]) as Row[]);setSubs((s||[]) as Submission[]);setMaterials(m||0);setLoading(false)})()},[]);
 const grade=async(s:Submission)=>{const sb=getSupabaseBrowserClient();if(!sb)return;setSaving(s.id);const {error}=await sb.from('submissions').update({grade:s.grade,feedback:s.feedback,updated_at:new Date().toISOString()}).eq('id',s.id);if(error)alert(error.message);else setSubs(v=>v.map(x=>x.id===s.id?s:x));setSaving(null)};
 return <RoleGuard role="guru"><Shell><div className="container"><section className="dashboard"><div className="dash-top"><div><div className="eyebrow">Portal guru</div><h1>Kelola pembelajaran.</h1><p className="muted">Tugas, materi, submission, nilai, dan feedback terhubung ke Supabase.</p></div><div className="toolbar"><Link className="button button-dark" href="/guru/materi">Kelola materi</Link><Link className="button button-dark" href="/guru/tugas">Kelola tugas</Link></div></div><div className="mini-stats"><div className="mini-stat"><span className="tag">Tugas</span><strong>{loading?'—':tasks.length}</strong><span className="muted">tersimpan</span></div><div className="mini-stat"><span className="tag">Submission</span><strong>{loading?'—':subs.length}</strong><span className="muted">masuk</span></div><div className="mini-stat"><span className="tag">Materi</span><strong>{loading?'—':materials}</strong><span className="muted">tersimpan</span></div></div><div style={{marginTop:22}} className="card"><div className="tag">Tugas terbaru</div>{tasks.length?<div className="table-like">{tasks.map(t=><div className="row" key={t.id}><strong>{t.title}</strong><span>{t.classes?.[0]?.name||'Kelas'}</span><span>{t.deadline?new Date(t.deadline).toLocaleDateString('id-ID'):'Tanpa deadline'}</span></div>)}</div>:<p className="muted">Belum ada tugas di Supabase.</p>}</div><div style={{marginTop:18}} className="card"><div className="tag">Monitoring & penilaian</div>{subs.length?<div className="table-like">{subs.map(s=><div className="row" key={s.id}><div><strong>{s.profiles?.[0]?.full_name||s.student_id}</strong><div className="muted">{s.assignments?.[0]?.title||s.assignment_id}</div></div><input className="input" style={{maxWidth:110}} type="number" min="0" max="100" value={s.grade??''} onChange={e=>setSubs(v=>v.map(x=>x.id===s.id?{...x,grade:e.target.value===''?null:Number(e.target.value)}:x))}/><input className="input" value={s.feedback||''} placeholder="Feedback" onChange={e=>setSubs(v=>v.map(x=>x.id===s.id?{...x,feedback:e.target.value}:x))}/><button className="button button-dark" disabled={saving===s.id} onClick={()=>void grade(s)}>{saving===s.id?'Menyimpan...':'Simpan'}</button></div>)}</div>:<p className="muted">Belum ada submission siswa.</p>}</div></section></div></Shell></RoleGuard>}
